[package]
name = "pe042"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cucumber = "0.19.1"
futures = "0.3.28"

[[test]]
name = "steps"
harness = false
